### ISSUE TITLE
Make Action, WebRequestTracer extend java.lang.Closeable

### ISSUE THREAD

**Issue by michele-mancioppi** [Dynatrace/openkit-java#58]
Action#close() and WebRequestTracer#close() would simply delegate to Action#leaveAction() and WebRequestTracer#stop(), respectively.

This would make both objects transparently usable with try-with-resources in Java 7+ without breaking compatibility with Java 6.

**Comment by thomasgrassauer** [comment]
Thank you for your input. We added it to the backlog and include the change in the next version.

**Comment by stefaneberl** [comment]
The improvement has been implemented and is merged into master with pull request https://github.com/Dynatrace/openkit-java/pull/61 (commit https://github.com/Dynatrace/openkit-java/commit/b5e69af36a7157c1e55d1a994db3544a936d687d).

This issue will be closed as soon as the 1.1.0 release is available on GitHub.

**Comment by stefaneberl** [comment]
Release is available (see https://github.com/Dynatrace/openkit-java/releases/tag/v1.1.0). Therefore I'm closing this issue.
